### ISSUE TITLE
Reply.from inside async handler cause Promise may not be fulfilled with 'undefined' when statusCode is not 204

### ISSUE THREAD

**Issue by NamNgKh** [fastify/fastify-reply-from#105]
## 🐛 Bug Report

when using reply.from inside async request handler will cause error "Promise may not be fulfilled with 'undefined' when statusCode is not 204"

## To Reproduce

the handle code:
/node_modules/fastify/lib/wrapThenable.js:30:30
```js
 `server.get('/', async (req, reply) => {
            //...some code here
            reply.from('<other url>');
});`
```

## Expected behavior

no error message

## Your Environment

- *node version*: 10
- *fastify version*: 3.6.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
you should do `return reply` at the end.

**Comment by NamNgKh** [comment]
thank @mcollina

**Comment by SimenB** [comment]
Can that be added to the error message somehow?

**Comment by mcollina** [comment]
> Can that be added to the error message somehow?

Yes, definitely. On this topic there is https://github.com/fastify/fastify/issues/2860 if you want to refactor that area of Fastify.
