### ISSUE TITLE
Proxying requests to multiple servers

### ISSUE THREAD

**Issue by apla** [fastify/fastify-reply-from#11]
Hi, I would like to proxy some requests to one host and some to another. Seems like it is impossible with current design. I can write code to support this feature, but want to discuss possible design first.

**Comment by apla** [comment]
For me, best option to have is just add hostname to `from` decorator. But in this case all options will be the same for all upstreams. So, initial plugin configuration should contain configurations for all upstreams. Like this:

```js
// single upstream
proxy.register(require('fastify-reply-from'), {
  base: 'http://localhost:3001/'
})

proxy.get('/', (request, reply) => {
  reply.from('/')
})

// multiple upstreams
proxy.register(require('fastify-reply-from'), [{
  base: 'http://localhost:3001/'
}, {
  base: 'http://localhost:5001/'
}])

proxy.get('/x3/', (request, reply) => {
  reply.from('http://localhost:3001/', '/')
})

proxy.get('/x5/', (request, reply) => {
  reply.from('http://localhost:5001/', '/')
})

```

**Comment by mcollina** [comment]
What you need is currently supported with the following:

```
// multiple upstreams

async function v3 (f) {
  f.register(require('fastify-reply-from'), {
    base: 'http://localhost:3001/'
  })

  proxy.get('/', (request, reply) => {
    reply.from('/')
  })
}


async function v5 (f) {
  f.register(require('fastify-reply-from'), {
    base: 'http://localhost:5001/'
  })

  proxy.get('/', (request, reply) => {
    reply.from('/')
  })
}

proxy.register(v3, { prefix: '/v3' })
proxy.register(v5, { prefix: '/v3' })
```

If multiple destinations are passed, I  would expect the servers to be functionally identical and `from` to load balance them in a round-robin fashion.

**Comment by delvedor** [comment]
Hi! Thank you for contributing!
I think that we could add a `name` option in addition to `base`, and then use that name inside reply. I think is a more clean API.
```js
proxy.register(require('fastify-reply-from'), [{
  base: 'http://localhost:3001/',
  name: 'users'
}, {
  base: 'http://localhost:5001/',
  name: 'events'
}])

proxy.get('/x3/', (request, reply) => {
  reply.from('users', '/')
})

proxy.get('/x5/', (request, reply) => {
  reply.from('events', '/')
})
```

@mcollina I like your idea, but what if we need to proxy request to services with completely different scopes?

**Comment by mcollina** [comment]
> @mcollina I like your idea, but what if we need to proxy request to services with completely different scopes?

You are right. But I would prefer something like: 

```js
proxy.register(require('fastify-reply-from'), [{
  base: 'http://localhost:3001/',
  name: 'users'
}, {
  base: 'http://localhost:5001/',
  name: 'events'
}])

proxy.get('/x3/', (request, reply) => {
  reply.from.users('/')
})

proxy.get('/x5/', (request, reply) => {
  reply.from.events('/')
})
```

This is similar to what we have done for the database drivers.

**Comment by ezequielavilagarcia** [comment]
So.. what's happens with this? It's a really cool feature and we really need it..

Thanks

**Comment by Eomm** [comment]
Would you like to send a PR? 💪

**Comment by franciscolourenco** [comment]
Are you aware that the following is currently possible?

```javascript
proxy.register(require('fastify-reply-from'))

proxy.get('/x3/', (request, reply) => {
  reply.from('http://localhost:3001/')
})

proxy.get('/x5/', (request, reply) => {
  reply.from('http://localhost:5001/')
})
```
