### ISSUE TITLE
The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received [Object: null prototype]

### ISSUE THREAD

**Issue by donghc** [fastify/fastify-reply-from#117]
## 🐛 Bug Report

When using HTTP, the request type is content- Type:application/x-www-form-urlencoded , Buffer.byteLength (body) error: the "string" argument must be of type string or an instance of buffer or arraybuffer. Received [object: null prototype]

## To Reproduce

```
curl -X POST "http://127.0.0.1:3000/changeSignStatus" -H "accept:*/*" -H "Content-Type:application/x-www-form-urlencoded; charset=UTF-8" -d "key=1152&status=1"
```

## Your Environment

- *node version*: v14.4.0
- *fastify version*: ^3.8.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
Can you provide an example on how to reproduce the problem? Note that you need a content-type parser to pass this through successfully - see fastify-http-proxy.

**Comment by donghc** [comment]
I'm sorry for the delay. This is an error report. This is another plug-in problem.

**Comment by donghc** [comment]
> 您能否提供一个有关如何重现该问题的示例？请注意，您需要一个内容类型解析器才能成功通过此解析器-请参见fastify-http-proxy。
for example
```
const Fastify = require('fastify')
const server = Fastify({logger:true})
const reply_form = require('fastify-reply-from')

server.register(require('fastify-formbody'))
server.register(reply_form)
server.register(require('fastify-http-proxy'), {
    upstream: 'http://division-test.haojile.net.cn/',
    prefix: '/division', // optional
    rewritePrefix: '/api/division',
    http2: false // optional
})

server.listen(3000)
```
```
curl -X POST "http://127.0.0.1:3000/division/global/changeSignStatus" -H "accept:*/*" -H "Content-Type:application/x-www-form-urlencoded; charset=UTF-8" -d "key=1152&status=1"
```

**Comment by donghc** [comment]
I find index.js Line 79 in the file，        
```
body = shouldEncodeJSON ? JSON.stringify(this.request.body) :this.request.body 
headers['content-length'] = Buffer.byteLength(body)
```
body is object，so throw an exception。

**Comment by mcollina** [comment]
There is some conflict with fastify-formbody, remove that and fastify-http-proxy would work.

**Comment by mcollina** [comment]
This needs a fix anyway, would you like to send a PR?

**Comment by donghc** [comment]
> This needs a fix anyway, would you like to send a PR?

I'm a rookie and I'd like to try.
