### ISSUE TITLE
request.from(...) to a fastify service with multipart/form-data leads to ECONNRESET

### ISSUE THREAD

**Issue by theliuk** [fastify/fastify-reply-from#118]
## 🐛 Bug Report

I configured two web services, both running on the top of the fastify ecosystem:

- `my-reverse-proxy`: uses `fastify-multipart` because some endpoints (not reported in the example) have to use it. If incoming requests respect some logic, these are forwarded to...
    
- `my-end-service`: handles a http `multipart/form-data` call carrying a file and some metadata

## To Reproduce
I prepared [this repo](https://github.com/theliuk/fastify-reply-from-bug-repr) and you can follow the instruction provided in the README.md file

See [this repo](https://github.com/theliuk/fastify-reply-from-bug-repr)

## Expected behavior

The request if forwarded by `fastify-reply-from` to the service which has to handle the call. 
This service can handle all the parts of the `multipart/form-data` correctly.

## Your Environment

    - node: erbium
    - fastify: v3.8.0
    - fastify-reply-from: v3.4.0
    - fastify-multipart: v3.3.1
    - docker-compose version 1.27.4, build 40524192

**Comment by Eomm** [comment]
What is the error?
Do you have any stacktrace?

Anyway I think the issue could be hidden here:

```
fastify.addHook('onRequest', async(req, res) => {
  //Perform some logic to decide wheter proxy the request or not
  return res.from('/')
})
```

`from` returns the `res` instance that is a thenable, so fastify is waiting to send something and this plugin is sending without notify fastify itself.

**Comment by theliuk** [comment]
> What is the error?
> Do you have any stacktrace? (EDIT: in which instance of the two)
> 
> Anyway I think the issue could be hidden here:
> 
> ```
> fastify.addHook('onRequest', async(req, res) => {
>   //Perform some logic to decide wheter proxy the request or not
>   return res.from('/')
> })
> ```
> 
> `from` returns the `res` instance that is a thenable, so fastify is waiting to send something and this plugin is sending without notify fastify itself.

Consider logs of container `my-reverse-proxy-container`.
Here the stacktrace:

```
Error: HTTP request timed out
at ClientRequest.<anonymous> (/usr/src/app/node_modules/fastify-reply-from/lib/request.js:88:19)
at Object.onceWrapper (events.js:420:28)
at ClientRequest.emit (events.js:314:20)
at Socket.emitRequestTimeout (_http_client.js:715:9)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:326:22)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)","type":"Error","msg":"response errored"}
```

```
GatewayTimeoutError: Gateway Timeout
at /usr/src/app/node_modules/fastify-reply-from/index.js:110:36
at ClientRequest.<anonymous> (/usr/src/app/node_modules/fastify-reply-from/lib/request.js:90:7)
at Object.onceWrapper (events.js:420:28)
at ClientRequest.emit (events.js:314:20)
at Socket.emitRequestTimeout (_http_client.js:715:9)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:326:22)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
```

**Comment by Eomm** [comment]
Ok, this stack let me think that the multipart route is not replying, I will check it better but it looks good at first check

**Comment by theliuk** [comment]
Related to this [PR](https://github.com/fastify/fastify-reply-from/pull/121). 
`fastify-reply-from` is not compatible with `fastify-multipart`; therefore, I'd close this issue.
