### ISSUE TITLE
follow-redirect usage via Agents doesn't work with fastify-reply-from

### ISSUE THREAD

**Issue by schickling** [fastify/fastify-reply-from#129]
## 🐛 Bug Report

It seems that using [follow-redirects](https://www.npmjs.com/package/follow-redirects) with fastify-reply-from doesn't work using the `new Agent()` mechanism.

## To Reproduce

```js
const Fastify = require('fastify').default
const { http, https } = require('follow-redirects')

const proxy = Fastify({
  logger: true,
})

proxy.register(require('fastify-reply-from').default, {
  http: {
    agents: { 'http:': new http.Agent(), 'https:': new https.Agent() },
  },
})
```

Using this setup the actual request-related code of `follow-redirects` is never called.

However I could get it to work using the following patch:

```patch
diff --git a/lib/request.js b/lib/request.js
index a202e4e9d0f6b2da852e33563cdb931eba5e6a76..81145c5206ee66c17cf5607384aa84cf2c3b70b5 100644
--- a/lib/request.js
+++ b/lib/request.js
@@ -1,7 +1,7 @@
 'use strict'
 const semver = require('semver')
-const http = require('http')
-const https = require('https')
+const http = require('follow-redirects/http')
+const https = require('follow-redirects/https')
 const querystring = require('querystring')
 const eos = require('end-of-stream')
 const pump = require('pump')
```

## Your Environment

- *node version*: 14.9.0
- *fastify version*: 3.9.2
- *fastify-reply-from*: 4.0.0
- *os*: Mac & Linux

**Comment by mcollina** [comment]
Would you like to understand what's the problem? This should work.
Note that this is covered by an unit test: https://github.com/fastify/fastify-reply-from/blob/master/test/http-agents.js.

**Comment by schickling** [comment]
That's what I initially concluded as well based on the unit tests I saw but it didn't work for me when using `follow-redirects`. The tests seem to work as they are based on the same `const http = require('http')` implementation but don't work for e.g. `const http = require('follow-redirects/http')`.

**Comment by mcollina** [comment]
Given how https://github.com/follow-redirects/follow-redirects/blob/master/index.js is implemented, I would be highly surprised it would work at all with this module :(. I'm deeply surprised it works with just patching the code - I would not expect it to.

**Comment by schickling** [comment]
I ended up using Nginx anyway for my use case, so I'm no longer blocked. Happy to close this if you think this is rather an issue with the `follow-redirects` package..

**Comment by mcollina** [comment]
Probably a better idea. Unless you need to run some JavaScript logic before/after the routing, NGINX is a significantly better proxy than anything we could ever wrote in JS.
