### ISSUE TITLE
ignore queryString options when url has search property already

### ISSUE THREAD

**Issue by vincent178** [fastify/fastify-reply-from#14]
Hi there,

is there any reason to return url.search directly here? https://github.com/fastify/fastify-reply-from/blob/master/index.js#L117-L124

My use case is that I want to append an access_token to the url in the proxy, but it got ignored when original url has queries, could you please explain a bit here?
```
proxy.all('/*', (request, reply) => {
  reply.from(request.req.url, {
    queryString: {
      access_token: request.cookies.access_token
    }
  })
})
```
even I specify the `queryString` here, it doesn't work because the above code.

Thanks,
Vincent

**Comment by vincent178** [comment]
https://github.com/fastify/fastify-reply-from/pull/15 first step fix.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify-reply-from/pull/15.
