### ISSUE TITLE
Host header should use the host property instead of hostname

### ISSUE THREAD

**Issue by vlad-cirstean** [fastify/fastify-reply-from#144]
## 🐛 Bug Report

The host header should be `<host>:<port>` acording to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host).
Right now the host header is obtained with `new URL(source).hostname` and it's missing the port ([see here](https://github.com/fastify/fastify-reply-from/blob/b79452919c8f0a6e641addcad608155f8028c82d/index.js#L50)). 
I think it should be obtained with `new URL(source).host`. 

## To Reproduce

```js
rewriteRequestHeaders(originalReq, headers){
    console.log(headers.host)
}

reply.from('http://127.0.0.1:8080' , {
    rewriteRequestHeaders
});
```

## Expected behavior

The header should be 127.0.0.1:8080 but instead it is 127.0.0.1

## Your Environment

- *node version*: 14.15.5
- *os*: Mac

**Comment by mcollina** [comment]
thanks! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
