### ISSUE TITLE
Documentation mismatch: reply.from options.body

### ISSUE THREAD

**Issue by mciocan** [fastify/fastify-reply-from#150]
## 🐛 Bug Report

Hello!
There is a documentation mismatch for reply.from [options.body field](https://github.com/fastify/fastify-reply-from/#body).

> #### `body`
> Replaces the original request body with what is specified. Unless
> [`contentType`][contentType] is specified, the content will be passed
> through `JSON.stringify()`.
> **Setting this option will not verify if the http method allows for a body**. 

But, if **body** is defined for a GET request, an [error will be thrown](https://github.com/fastify/fastify-reply-from/blob/master/index.js#L85):
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Rewriting the body when doing a GET is not allowed"
}
```

I've read https://github.com/fastify/fastify/issues/953 and I understand that Fastify [will not process the body](https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L17) for GET requests (which is RFC compliant).

**My question: the docs should be updated OR if reply.from options.body is defined, to bypass body verification?**

We are using this amanzing HTTP stack(fastify, fastify-reply-from, undici) for a lot of projects and it's great.
But, for some legacy projects, where we have GET requests with body, we encountered some issues.

Thank you!

## To Reproduce

```js
const Fastify = require('fastify');

const upstream = Fastify({logger: true});

upstream.all('*', (request, reply) => {
  reply.send(`hello world: ${request.body}`)
});

upstream.listen(9090);


const server = Fastify({logger: true});
server.register(require('fastify-reply-from'), {base: 'http://localhost:9090'});

server.all('*', (request, reply) => {
  reply.from(request.url, {body: 'custom body'});
});

server.listen(8080);
```
```shell
curl --request GET 'http://localhost:8080/'
```
## Expected behavior
```
hello world: custom body
```

## Your Environment

- *node version*: 14.16.0
- *fastify version*: 3.13.0
- *fastify-reply-from version*: 5.0.1
- *os*: Mac

**Comment by jsumners** [comment]
I think the docs should be updated.

**Comment by mcollina** [comment]
Yes, the doc should be updated. This is not supported.

**Comment by mciocan** [comment]
To be honest, I was expected for this answer! The right answer :)  

Should I add a PR?

**Comment by mciocan** [comment]
[PR](https://github.com/fastify/fastify-reply-from/pull/151) added.
- updated docs
- changed error message to respect HTTP method
- added tests for no options.body, HEAD method
