### ISSUE TITLE
Reply from fails when a query string is present in the source URL

### ISSUE THREAD

**Issue by sanpablomarket** [fastify/fastify-reply-from#154]
## 🐛 Bug Report

URL's with a query string source fail to be proxied.  Specifically this is being called from `fastify-http-proxy` but I believe this is a bug in `fastify-reply-from`.

## To Reproduce

1. Register `fastify-reply-from`
```js
fastify.register(From, { 
  upstream: 'http://localhost:8000/test',
  rewritePrefix: '/test',
  base: 'http://localhost:8000/test', 
});
```
2.  In a route handler
```js
reply.from('/test?some_query=1')
```
3. The `buildURL` util throws an error, I believe in error. In this case
`dest.href` is `http://localhost:8000/test?some_query=1` and it does not start with `http://localhost:8000/test/` (a trailing slash was appended even though its a non relative url.

Without knowing a ton about how the plugin is supposed to function it seems like checking for the presence of a query string on `dest` before trying to append a trailing slash would fix the issue.

## Expected behavior

I would expect this not to throw an error, and the request to be proxied to the url with the query string maintained.

## Your Environment

- *node version*: 12.14.0
- *fastify version*: 3.12.0
- *os*: Mac
- *other info* `fastify-reply-from` is being called by `fastify-http-proxy` `5.0.0` in this case.

**Comment by nherment** [comment]
@mcollina could you please confirm that this is a bug? I suspect this was made on purpose.
The library does allow rewriting the query string the same way it allows rewriting the headers and the body.

@sanpablomarket here is how you could pass additional query params to the target server:

```js
reply.from('/test', {
  queryString: {
    ...request.query, // the proxied request, only needed if you want to keep the original query args
    some_query: 1
  }
})
```

Admittedly, it feels natural to do what you suggests @sanpablomarket and add query params to the `reply.from()` URL but the way to pass query params is consistent and clearly explained in the readme.

**Comment by mcollina** [comment]
@nherment I agree that this is not supported. However, It's a bug in the sense that it should throw a meaningful error rather than something obscure.

**Comment by nherment** [comment]
@sanpablomarket I'm unable to reproduce this issue.

The code is behaving the same way you expect it to. There is already a test case covering your example [here](https://github.com/fastify/fastify-reply-from/blob/ceac341e67f9927470ff6bea10c16f8584a7e2a9/test/full-querystring-rewrite-string.js#L25). I also tried the test case with the same plugin options as you.

In addition, I looked at `fastify-http-proxy` and it is using a version of this `fastify-reply-from` plugin that behaves as expected.

Am I missing anything?

**Comment by nherment** [comment]
Updated test case with the same options as parent:

```js
'use strict'

const t = require('tap')
const Fastify = require('fastify')
const From = require('..')
const http = require('http')
const get = require('simple-get').concat
const { test } = require('tap')

const instance = Fastify()


t.plan(10)
t.tearDown(instance.close.bind(instance))

const target = http.createServer((req, res) => {
  t.pass('request proxied')
  t.equal(req.method, 'GET')
  t.equal(req.url, '/hello?c=d')
  res.statusCode = 205
  res.setHeader('Content-Type', 'text/plain')
  res.setHeader('x-my-header', 'hello!')
  res.end('hello world')
})

instance.get('/hello', (request, reply) => {
  reply.from('/hello?c=d')
})

t.tearDown(target.close.bind(target))

target.listen(0, (err) => {
  t.error(err)

  instance.register(From, {
    base: `http://localhost:${target.address().port}`,
    upstream: `http://localhost:${target.address().port}/test`,
    rewritePrefix: '/test',
  })

  instance.listen(0, (err) => {
    t.error(err)

    get(`http://localhost:${instance.server.address().port}/hello?a=b`, (err, res, data) => {
      t.error(err)
      t.equal(res.headers['content-type'], 'text/plain')
      t.equal(res.headers['x-my-header'], 'hello!')
      t.equal(res.statusCode, 205)
      t.equal(data.toString(), 'hello world')
    })
  })
})

```

**Comment by simone-sanfratello** [comment]
@sanpablomarket what is the `rewritePrefix` option? I don't see that in the code

**Comment by simone-sanfratello** [comment]
@sanpablomarket the issue is not clear to me, looks like you are trying to use options of `fastify-http-proxy` in this plugin, is it?
