### ISSUE TITLE
Add a hook to set the upstream base url based on the request data

### ISSUE THREAD

**Issue by yohay-ma** [fastify/fastify-reply-from#158]
## 🚀 Feature Proposal

Add a hook to set the upstream base url based on the request data

## Motivation

Needed for a gradual rollout of services.

For example:
instance: http://localhost:3000/test
service A: http://localhost:3001/test
service B: http://localhost:3002/test

I'd like to set 20% of the requests to go to http://localhost:3001/test and 80% to go to http://localhost:3001/test

In this case the getUpstream will do a random of 20%/80% between the two

see PR: https://github.com/fastify/fastify-reply-from/pull/157

**Comment by climba03003** [comment]
Resolved by #157
