### ISSUE TITLE
Using `rewriteRequestHeaders` with async/await does not work properly

### ISSUE THREAD

**Issue by vorillaz** [fastify/fastify-reply-from#168]
## 🐛 Bug Report

It seems that when using an `async` callback for `rewriteRequestHeaders` an empty object gets returned and the API overrides the headers. Original I found bug while using https://github.com/fastify/fastify-http-proxy

## To Reproduce

```js
const geoip = require("fast-geoip");
const Fastify = require("fastify");

const target = Fastify({
	logger: true,
});

target.get("/", (request, reply) => {
  console.log(request.headers);
	reply.send("hello world");
});

const proxy = Fastify({
	logger: true,
});

proxy.register(require("fastify-reply-from"), {
	base: "http://localhost:3001/",
	rewriteRequestHeaders: async (request, headers) => {
		const {country} = await geoip.lookup("192.11.111.111");
                return {...headers, country, time: Date.now()}
	},
});
```

## Expected behavior
Expecting to receive the headers from the upstream along with `country` and `time` headers

## Your Environment

- *node version*: 14
- *fastify version*: latest
- *os*: Mac

**Comment by mcollina** [comment]
This function is (currently) synchronous. I would recommend you to use a preHandler hook to implement geolocation instead and decorate the request.
