### ISSUE TITLE
Content-Type is set to application/octet-stream for requests with no body

### ISSUE THREAD

**Issue by kutyepov** [fastify/fastify-reply-from#174]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

14.5.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

If target server replies with status code 204 and empty response body, `content-type: application/octet-stream` header is added by fastify to the response.
res.stream is passed to .send() [here](https://github.com/fastify/fastify-reply-from/blob/master/index.js#L155), which contains `.pipe()` method that makes fastify erroneously set the above mentioned header [here](https://github.com/fastify/fastify/blob/main/lib/reply.js#L136-L138)

![image](https://user-images.githubusercontent.com/10676515/118170838-95b72080-b3f8-11eb-8e5f-da50b5e66fbd.png)

and as can be seen on the screenshot below, if target server is pinged directly, the response doesn't have content-type header at all, which is correct.

![image](https://user-images.githubusercontent.com/10676515/118171040-d878f880-b3f8-11eb-8690-4b3b1c3bab6a.png)

### Steps to Reproduce

```
const Fastify = require('fastify')

const target = Fastify({
    logger: true
})

target.get('/', (request, reply) => {
    // added status 204 here
    reply.status(204).send();
})

const proxy = Fastify({
    logger: true
})

proxy.register(require('fastify-reply-from'), {
    base: 'http://localhost:3001/'
})

proxy.get('/', (request, reply) => {
    reply.from('/')
})

target.listen(3001, (err) => {
    if (err) {
        throw err
    }

    proxy.listen(3000, (err) => {
        if (err) {
            throw err
        }
    })
})
```

### Expected Behavior

Content-Type header should not be set for responses with status code 204 since there's no actual content sent.

**Comment by mcollina** [comment]
Good spot!

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by kutyepov** [comment]
@mcollina sure, will raise a PR shortly.

**Comment by kutyepov** [comment]
@mcollina so, I tried to prototype a fix for this and realized that it would be best to discuss a possible solution here first.

So far, I have a few solutions in mind.

1. Try to read from the stream assuming that it should not have any content. Something along the lines of code shown below. In this case it will get `null` from the stream and things will work out fine on fastify's end. The obvious drawback here is that it can potentially read the actual data from the stream. 

```diff
diff --git a/index.js b/index.js
index 4723b55..e05632c 100644
--- a/index.js
+++ b/index.js
@@ -152,7 +152,8 @@ module.exports = fp(function from (fastify, opts, next) {
       if (onResponse) {
         onResponse(this.request.raw, this, res.stream)
       } else {
-        this.send(res.stream)
+        const shouldAttemptToReadStream = res.statusCode === 204 && !res.headers['Content-Type'];
+        this.send(shouldAttemptToReadStream ? res.stream.read() : res.stream)
       }
     })
     return this
```

2. Drop the response body from the payload if there shouldn't be any data as per spec of the given HTTP status code. Pretty much the same approach but w/o risking to read data from the stream.

```diff
diff --git a/index.js b/index.js
index 4723b55..e05632c 100644
--- a/index.js
+++ b/index.js
@@ -152,7 +152,8 @@ module.exports = fp(function from (fastify, opts, next) {
       if (onResponse) {
         onResponse(this.request.raw, this, res.stream)
       } else {
-        this.send(res.stream)
+        const shouldOmitResponseBody = res.statusCode === 204 && !res.headers['Content-Type'];
+        this.send(shouldOmitResponseBody ? null : res.stream)
       }
     })
     return this
```


I am not happy with both of these solutions as the plugin now makes assumptions about the request, whilst it should just proxy it as is, so perhaps it is better to fix this on fastify's end? Something along the lines of

```diff
diff --git a/lib/reply.js b/lib/reply.js
index 555b099..7e114dd 100644
--- a/lib/reply.js
+++ b/lib/reply.js
@@ -131,10 +131,11 @@ Reply.prototype.send = function (payload) {
 
   const contentType = this.getHeader('content-type')
   const hasContentType = contentType !== undefined
+  const shouldHaveContentType = !hasContentType && this.statusCode !== 204
 
   if (payload !== null) {
     if (Buffer.isBuffer(payload) || typeof payload.pipe === 'function') {
-      if (hasContentType === false) {
+      if (hasContentType === false && shouldHaveContentType) {
         this[kReplyHeaders]['content-type'] = CONTENT_TYPE.OCTET
       }
       onSendHook(this, payload)
```

However, it feels like it narrowly addresses the problem of what is passed to the `.send()` method from reply-from plugin.

Given all that, I will appreciate some guidance on the possible solution for this.

What would be the best place to fix this: `fastify-reply-from` or `fastify`? What would be a preferred approach 1, 2, 3 or am I missing something obvious and a lot easier?

Note: I am checking just for 204 status code in all my examples, but in concrete implementation it should include other codes where content is not expected.

**Comment by mcollina** [comment]
I think we should just stop adding a content-type where there is not one. Wdyt?

**Comment by simoneb** [comment]
Good analysis @kutyepov. What about changing this library so that when we infer that there is no content we don't send anything? This inference can be done using transfer-encoding and content-length, as per the spec https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2.

I would also tend to agree that this change may [live in fastify, as you mentioned](https://github.com/fastify/fastify/blob/a5386e4720fdbebca1ccd1d3925f118ff7f0b19d/lib/reply.js#L136-L141).

Fastify seems to assume that if you `reply.send(stream)` and there isn't a content type already, it will set it to octet-stream even if the stream is empty, which doesn't sound correct. On the other hand I'm not sure how Fastify could predict whether the stream is going to be empty or not, but that's probably something that @mcollina may have a better grasp on.

**Comment by mcollina** [comment]
I think we can change it in Fastify.

**Comment by mcollina** [comment]
I think the best approach is to drop the automatic setting of the Content Type in Fastify for streams. Target the branch `next` as it's a semver-major change.

**Comment by simoneb** [comment]
@mcollina do you mean unconditionally dropping the inference of the content type response header when the argument to reply.send is a stream? or applying a more refined logic?

**Comment by mcollina** [comment]
> do you mean unconditionally dropping the inference of the content type response header when the argument to reply.send is a stream? 

Exactly that. A user can set this if they need to. Bonus point, put it behind an option of v3 and swap the default in v4.

**Comment by simoneb** [comment]
@kutyepov since you started looking into this, would you be interested in contributing this change to fastify?

**Comment by simoneb** [comment]
@kutyepov this change landed in fastify's next branch, meaning that it will be available in the next major release.

**Comment by mcollina** [comment]
I'm going to close this as done.

**Comment by kutyepov** [comment]
Awesome! Sorry for the delay in response, I have been away for a while and just catching up with GH notifications.
