### ISSUE TITLE
Use a custom undici instance

### ISSUE THREAD

**Issue by dnlup** [fastify/fastify-reply-from#192]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

👋🏻 Thank you for this awesome package! I was thinking that it could be useful to allow to pass a custom `undici` instance  in addition to or as an alternative to the custom options already available. WDYT?

### Motivation

The first 2 reasons that come to mind are:

* use a `mockedClient` in tests
* re-use an instance already initialised in the app

**Comment by mcollina** [comment]
Sure, good idea! Would you like to send a PR?

**Comment by dnlup** [comment]
Yes, I'll work on it 😉

**Comment by simonecorsi** [comment]
Following, let me know if you need some help!

**Comment by dnlup** [comment]
I was thinking about using an option called `instance` in the `undici` object. Otherwise the `undici` key could point to the instance, but it would complicate the checks done in `buildRequest`.
