### ISSUE TITLE
Handle 503 and Retry-After header

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-reply-from#193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

After receiving a 503, we might want to retry sending that request after a short delay.

This should be done for GET requests.

**Comment by leorossi** [comment]
I am working on this.
Should _all_ GET requests be retried? What happens when specifically configured not to retry?
What if `Retry-After` header is not set?

**Comment by mcollina** [comment]
> Should all GET requests be retried? 

Ideally yes

> What happens when specifically configured not to retry?

How is this configuration happen? Ideally we should support a flag to avoid retries and set a maximum time to retry.

**Comment by mcollina** [comment]
If there is no Retry-After, just retry after `42` ms and then use exponential backoff.

**Comment by leorossi** [comment]
From test:

`instance.register(From, { undici: true, retryMethods: ['DELETE'] })`

In this case, should I still retry on GET and a 503 response?

**Comment by mcollina** [comment]
I don't understand the question.

**Comment by leorossi** [comment]
So, you can specify to the plugin which methods needs to be _retried_ . 
Do we want to retry always the `GET` methods even though the user specified _not_ to retry it?

**Comment by mcollina** [comment]
nope, the users win
