### ISSUE TITLE
Suggestion: rewriteHeaders should take originalReq as argument

### ISSUE THREAD

**Issue by csvan** [fastify/fastify-reply-from#223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, rewriteHeaders - which rewrites response headers - only takes the `headers` object as an argument. Meanwhile, rewriteRequestHeaders - which rewrites request headers - takes an additional `originalReq` parameter which includes the request object.

I suggest that both methods should have the same signature.

### Motivation

In a lot of use cases, we want to perform some kind of manipulation of response headers, where request context is relevant. For example, we may want to modify the `location` header in a redirect based on some external header passed in the request. This is not possible if the request object is not available.

Also, it just looks nicer if two symmetric methods have the same signature.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by csvan** [comment]
Sorry @mcollina I completely missed this, thanks @AlisaLC for the fix and sorry you had to work on it
