### ISSUE TITLE
Docs (potentially code) and Typescript definition not in sync

### ISSUE THREAD

**Issue by maxfrigge** [fastify/fastify-reply-from#233]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Some of the plugin options seem to be missing in [index.d.ts](https://github.com/fastify/fastify-reply-from/blob/master/index.d.ts). I am just comparing the docs vs type definitions, but it seems that the docs are in line with the code.

**These types are defined:**

```typescript
export interface FastifyReplyFromOptions {
  base?: string;
  cacheURLs?: number;
  disableCache?: boolean;
  http?: HttpOptions;
  http2?: Http2Options | boolean;
  undici?: Pool.Options;
  keepAliveMsecs?: number;
  maxFreeSockets?: number;
  maxSockets?: number;
  rejectUnauthorized?: boolean;
  sessionTimeout?: number;
  contentTypesToEncode?: string[];
}
```

**Here is the list of options according to your docs:**

- `base`
- `undici`
- `http`
- `http2`
- `cacheURLs`
- `disableCache`
- `contentTypesToEncode`
- `retryMethods`
- `maxRetriesOn503`

**Defined in `index.d.ts` but NOT in docs:**

- `keepAliveMsecs`
- `maxFreeSockets`
- `maxSockets`
- `rejectUnauthorized`
- `sessionTimeout`

**Defined in docs but NOT in `index.d.ts`:**

- `retryMethods`
- `maxRetriesOn503`

**Comment by RafaelGSS** [comment]
Good catch!

Would you like to send a Pull Request to address this issue? Remember to add unit tests.
