### ISSUE TITLE
[Undici] Stream body support 

### ISSUE THREAD

**Issue by artur-ma** [fastify/fastify-reply-from#238]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently this lib does not support body stream/pipe, e.g if I want to upload some zip file to target service through the gateway, AFAIK there is no way to do it.

But Undici supports pipelining out of the box, so its pretty easy to implement body streaming, should we add this feature only for undici? WDYT?

### Motivation

Body streaming is harder to implement with native http but easier with undici, this is useful feature that is supported by many proxy libraries.

### Example

```js
proxy.addContentTypeParser('zip', (req, payload, done) => {
  done();
})

 proxy.put('/', (request, reply) => {
  pipeline(request.raw, undiciPipeline(
    'http://localhost:3333' ,{
    path: '/',
    method: 'PUT',
  }, ({ statusCode, headers, body }) => {
    console.log(`response received ${statusCode}`)
    console.log('headers', headers)

    reply.status(statusCode).headers(headers);

    return body;
  }), (duplex) => {
    reply.send(duplex)
  }, console.error)
})
 ```
 
 If we could specify  on initialization which content-type should be piped, then we can apply this logic

**Comment by climba03003** [comment]
Interesting thing is that passing stream in option is not supported.
https://github.com/fastify/fastify-reply-from/blob/8562c747e3c482054c06479516b153d6667b8420/index.js#L70-L72

But, the stream from `request.body` itself is supported.
https://github.com/fastify/fastify-reply-from/blob/8562c747e3c482054c06479516b153d6667b8420/index.js#L89-L91

**Comment by artur-ma** [comment]
Yes, you are right I just overcomplicated things, sorry

closing
