### ISSUE TITLE
Header encoding changes, leading to `ERR_INVALID_CHAR`

### ISSUE THREAD

**Issue by SimenB** [fastify/fastify-reply-from#287]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Plugin version

8.3.1

### Node.js version

16.19.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

When a header is set using a character like `å` (Norwegian character) its encoding gets messed up. A fastify server serving it serializes correctly, but if `reply-from` is used, the encoding changes. If another server with `reply-from` is chained, the app crashes with `TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["content-disposition"]`.

### Steps to Reproduce

```js
const replyFrom = require('@fastify/reply-from');
const fastify = require('fastify');

const app = fastify();

app.get('/', (_request, reply) => {
  reply.header('content-disposition', 'år.pdf').send('OK');
});

app.listen({ port: 6666 });

const proxy = fastify();

proxy.register(replyFrom);

proxy.get('/', (_request, reply) => {
  return reply.from('http://localhost:6666');
});

proxy.listen({ port: 7777 });

const secondProxy = fastify();

secondProxy.register(replyFrom);

secondProxy.get('/', (_request, reply) => {
  return reply.from('http://localhost:7777');
});

secondProxy.listen({ port: 8888 });
```

```sh-session
$ curl -i http://localhost:6666
HTTP/1.1 200 OK
content-disposition: år.pdf
content-type: text/plain; charset=utf-8
content-length: 2
Date: Fri, 27 Jan 2023 15:47:49 GMT
Connection: keep-alive
Keep-Alive: timeout=72


$ curl -i http://localhost:7777
HTTP/1.1 200 OK
content-disposition: r.pdf
content-type: text/plain; charset=utf-8
content-length: 2
date: Fri, 27 Jan 2023 15:47:52 GMT
connection: keep-alive
keep-alive: timeout=72


$ curl -i http://localhost:8888
curl: (52) Empty reply from server
```

### Expected Behavior

The header should be correctly encoded and decoded (i.e. `7777` and `8888` should have the same result as `6666`).

If that's not possible I expect the first server to complain when the header is added.

**Comment by mcollina** [comment]
Ouch! have you got a full stack trace? Would you like to send a PR?

**Comment by SimenB** [comment]
Stack trace:

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["content-disposition"]
    at storeHeader (node:_http_outgoing:572:5)
    at processHeader (node:_http_outgoing:567:3)
    at ServerResponse._storeHeader (node:_http_outgoing:457:11)
    at ServerResponse.writeHead (node:_http_server:387:8)
    at onSendEnd (/Users/simen/repos/monorepo/node_modules/fastify/lib/reply.js:596:7)
    at onSendHook (/Users/simen/repos/monorepo/node_modules/fastify/lib/reply.js:529:5)
    at fallbackErrorHandler (/Users/simen/repos/monorepo/node_modules/fastify/lib/error-handler.js:130:3)
    at handleError (/Users/simen/repos/monorepo/node_modules/fastify/lib/error-handler.js:60:5)
    at onErrorHook (/Users/simen/repos/monorepo/node_modules/fastify/lib/reply.js:742:5)
    at _Reply.Reply.send (/Users/simen/repos/monorepo/node_modules/fastify/lib/reply.js:133:5
```

**Comment by mcollina** [comment]
HTTP Headers are not supposed to contain UTF-8 characters. 

There are two bugs:

1. the first server actually sending this header out without throwing. I guess we bypass this check in Fastify for throughput reasons... we might rethink it.
2. the second server should definitely catch the error while it validates this.

**Comment by climba03003** [comment]
This issue https://github.com/fastify/fastify/issues/3808 just pop up in my memory when seeing non-ASCII string in header.

> the first server actually sending this header out without throwing. I guess we bypass this check in Fastify for throughput reasons... we might rethink it.

According to the research  from that issue https://github.com/nodejs/node/issues/42579
If there is "Transfer-Encoding: chunked" header (exactly chunked) setHeader works properly, it sets the input header (ByteString) as is.

I assume we are not bypass anything in `fastify` but node.js just serialize the output from the above statement.

> the second server should definitely catch the error while it validates this.

We need to think why only chaining will not set `Transfer-Encoding: chunked`.

**Comment by climba03003** [comment]
I still see it as a upstream bug from `node.js`.
It treats the header differently when there is a header of `Transfer-Encoding` or not.

It should throw no matter the header `Transfer-Encoding` exists.

**Comment by mcollina** [comment]
@climba03003 could you open an issue on Node.js describing the problem?

**Comment by SimenB** [comment]
Ah, based on the links in the Node issue, adding `encodeURIComponent` works. 👍 A bit too aggressive (e.g. encoding spaces etc.), but doesn't hurt I think. At least the file from Chrome is named correctly by it.

---

Note that `content-disposition` does not pick this up (possibly https://github.com/jshttp/content-disposition/issues/27) so `@fastify/static`'s `reply.download` will produce an invalid header if the filepath includes utf-8 characters

https://github.com/fastify/fastify-static/blob/c95eaf7bf20489007c7d85f5516c421b2d6b4334/index.js#L306-L307

**Comment by climba03003** [comment]
`content-disposition` should be encoding the utf-8 character from it's claim.

When the `latin1` is not same as `input`, it pass to `filename*` field.
https://github.com/jshttp/content-disposition/blob/73bf21e7c3f55f754932844584061027767289f4/index.js#L203-L205

When there is a `filename*` field, it use percent encode.
https://github.com/jshttp/content-disposition/blob/73bf21e7c3f55f754932844584061027767289f4/index.js#L246-L248

**Comment by mcollina** [comment]
Should we fork content-disposition?

**Comment by climba03003** [comment]
`content-disposition` actually works as intended.
The character [`å`](https://github.com/nodejs/node/blob/ba565a37349e81c9d2402b0c8ef05ab39dca8968/lib/_http_common.js#L220) also allowed from `node` itself.

I assume some weird conversion happen between. High possibility the problem is cause by `undici`.

**Comment by SimenB** [comment]
`å` is not the same character code in `latin1` and `utf8`, so there needs to be some sort of transcoding (or usage of `filename*=utf-8`)

```js
const {transcode: bufferTranscode} = require('node:buffer');

const utf8Buffer = Buffer.from('å');
const latin1Buffer = bufferTranscode(utf8Buffer, 'utf8', 'latin1');

console.log(Buffer.compare(utf8Buffer, latin1Buffer)); // logs -1
```

**Comment by climba03003** [comment]
It still confuse me why the first comparison is `true` if the byte should not be the same.
Only after the second write to the header, it becomes totally wrong.

```js
const contentDeposition = require('content-disposition')
const http = require('http')
const { request } = require('undici')

const header = contentDeposition('år.pdf')

http.createServer(function(_, response) {
  response.writeHead(200, {
    'content-length': 2,
    'content-disposition': header
  })
  response.end('OK')
}).listen({ port: 6666 })

http.createServer(async function(_, response) {
  const { statusCode, headers, body } = await request('http://localhost:6666', {
    method: "GET"
  })
  console.log(headers)
  console.log(headers['content-disposition'] === header) // true
  delete headers['transfer-encoding']
  response.writeHead(statusCode, headers)
  body.pipe(response)
}).listen({ port: 7777 })

http.createServer(async function(_, response) {
  const { statusCode, headers, body } = await request('http://localhost:7777', {
    method: "GET"
  })
  console.log(headers)
  console.log(headers['content-disposition'] === header) // false
  delete headers['transfer-encoding']
  response.writeHead(statusCode, headers)
  body.pipe(response)
}).listen({ port: 8888 })
```

**Comment by SimenB** [comment]
When fetching `7777` you can see the header has lost the character

```sh-sesion
$ curl -i http://localhost:7777
HTTP/1.1 200 OK
content-length: 2
content-disposition: attachment; filename="r.pdf"
date: Mon, 30 Jan 2023 10:42:49 GMT
connection: keep-alive
keep-alive: timeout=5

OK
```

I think this is just bad printing by `curl`. Using e.g. `httpie` shows this.

```sh-session
$ http http://localhost:6666
HTTP/1.1 200 OK
Connection: keep-alive
Date: Mon, 30 Jan 2023 10:44:26 GMT
Keep-Alive: timeout=5
content-disposition: attachment; filename="Ã¥r.pdf"
content-length: 2

OK


$http http://localhost:7777
HTTP/1.1 200 OK
connection: keep-alive
content-disposition: attachment; filename="år.pdf"
content-length: 2
date: Mon, 30 Jan 2023 10:44:35 GMT
keep-alive: timeout=5

OK
```

`6666` gives no `å`, while `7777` it's back. `8888` still crashes of course, regardless of `curl` vs `httpie` (thankfully 😅).

So I do think there's some encoding issue here, and I do think `content-disposition` should deal with it (and ideally node would validate of course)

**Comment by climba03003** [comment]
`curl` is showing the `UTF-8` character but `httpie` is showing the `Latin1` character.
Weird, since inside the `7777` server log, it is properly received as `UTF-8` byte.

**Comment by climba03003** [comment]
I see the problem, whenever you pipe with a `stream` to response.
The encoding is actually changed.

So, `6666` is display correctly. `7777` received correctly, but since it `pipe` with `stream`. It sent out wrongly.

**Comment by SimenB** [comment]
Can confirm that this is fixed by https://github.com/nodejs/undici/pull/1911 (without #289 applied) 🎉
