### ISSUE TITLE
Host and other request headers are incorrectly modified on the original request, not just the forwarded request

### ISSUE THREAD

**Issue by effulgentsia** [fastify/fastify-reply-from#291]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

8.4.2

### Node.js version

18

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Description

For an HTTP 1 request, the Reply decorator initializes the `headers` object for the request about to be sent to the upstream URL to [the same object as the original request's headers](https://github.com/fastify/fastify-reply-from/blob/v8.4.2/index.js#L77), and then sets `host` and other headers on this object, which means these headers are modified on the original request as well.

This means any further hooks that are called during the original request's lifecycle will see the original request as having these changes, which I think is incorrect since these changes are intended to be about what is being forwarded, not about modifying the semantics of the original request.

Concretely, I ran into this while trying to set an `x-forwarded-host` header on the forwarded request to the host of the original request by doing:
```
rewriteRequestHeaders(originalReq, headers) {
  return {
    ...headers,
    'x-forwarded-host': originalReq.headers.host,
  }
}
```

However, this doesn't work as expected, because by the time this runs, `originalReq.headers.host` has already been modified [to the host of the upstream URL](https://github.com/fastify/fastify-reply-from/blob/v8.4.2/index.js#L78).

### Steps to Reproduce

See the code snippet in the Description.

### Expected Behavior

I expect the [headers.host = url.host](https://github.com/fastify/fastify-reply-from/blob/v8.4.2/index.js#L78) line and other changes to `headers` in that function to only be for what gets sent to the upstream server, not change the original request. For example, by changing the line above that from:
```
const headers = req.headers
```

to:
```
const headers = Object.assign({}, req.headers)
```
or similar.

Or is my expectation incorrect?

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by effulgentsia** [comment]
I opened a PR in https://github.com/fastify/fastify-reply-from/pull/292

**Comment by effulgentsia** [comment]
Thank you for merging the PR and tagging a release!
