### ISSUE TITLE
Option to disable request timeout

### ISSUE THREAD

**Issue by deanhaleem** [fastify/fastify-reply-from#298]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Option to completely disable the request timeout (i.e. not pass anything in [`requestOptions.timeout`](https://github.com/fastify/fastify-reply-from/blob/master/lib/request.js#L268)).

### Motivation

We have an app that uses SSE, but it doesn't send requests directly to that server. It sends them to another server that uses `fastify-reply-from` to forward the request to the server that sends the events. Due to the persistent http connection, we'll always get a timeout error after whatever was configured for the `opts.http.requestOptions.timeout`.

We want to disable the timeout in this package because we still want to use this proxy requests to a from one server to another.

### Example

To avoid a breaking change, perhaps `timeout` could also be a `boolean`. So code that looks like below. Other options like allowing `null` to mean no timeout are there, but may break someone's code.

```js
// request.js line 267
if (
  // if timeout is not a boolean and falsy, use the default. 
  // if timeout is a boolean, use the default only if it's true
  typeof httpOpts.requestOptions.timeout !== 'boolean' && !httpOpts.requestOptions.timeout ||
  httpOpts.requestOptions.timeout
) {
  httpOpts.requestOptions.timeout = 10000
}
```
```js
// example usage
proxy.register(require('@fastify/reply-from'), {
  base: 'http://localhost:3001/'
  http: {
    requestOptions: {
      timeout: false
    }
  }
})
```

**Comment by mcollina** [comment]
I think the correct behavior is to completely remove the body timeout if the response has an header `Content-Type: text/event-stream`. I also think this might be a bug upstream in Undici and not in this module.

I personally do not have time to work on this right now. If you would like to send a PR it would be great.

**Comment by deanhaleem** [comment]
Makes sense, will look to get a PR out. Thanks
