### ISSUE TITLE
Pass the request to the queryString function

### ISSUE THREAD

**Issue by ttshivers** [fastify/fastify-reply-from#364]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be great to have access to the request object when passing a function for the `queryString` function in the same way that `rewriteRequestHeaders` has access to the request object.

### Motivation

I'd like to be able to set the queryString based on other data present in the request including potentially injected data from a `preHandler`.

### Example

```js
proxy.register(require('@fastify/reply-from'), {
  base: 'http://localhost:3001/',
  queryString(search, reqUrl, req) {
    return {
      authToken: req.authToken,
    };
  },
})
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ttshivers** [comment]
Yes I can make a PR for this.
