### ISSUE TITLE
fastify-reply-from library doesnt work when input is a file in post request. Gives error ""The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received [Object: null prototype]"

### ISSUE THREAD

**Issue by shalakad19** [fastify/fastify-reply-from#384]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.28.1

### Plugin version

^7.0.0

### Node.js version

18.18.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.7

### Description

```js
import fastifyReplyFrom from "@fastify/reply-from";
import fileUpload from "fastify-file-upload";
import upstreamUrl from "config"

async function uploadFile(server, options){
  server.register(fastifyReplyFrom);
  server.register(fileUpload);
  
  server.route({
    method: "POST",
    url: `/app/doc/release/*`,
    handler: (request, reply) => {
      const url = `${upstreamUrl}${request.raw.url.replace(‘/app/doc/release, '')}`;
      reply.from(url);
    }
  });
}
```

I am trying to upload a file and proxy it to another URL using fastify reply form. All other POST and GET requests work just fine with the @fastify/reply-from. Only for the request that accepts excel file as in input, I  am getting the below error

```json
{
    "statusCode": 500,
    "code": "ERR_INVALID_ARG_TYPE",
    "error": "Internal Server Error",
    "message": "The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received [Object: null prototype]"
}
```

So I changed the code to include request body and Content-Type:

```js
server.route({
    method: "POST",
    url: `/app/doc/release/`,
    handler: (request, reply) => {
     
      const url = `${upstreamUrl}${request.raw.url.replace('/app/doc/release', '')}`;
      reply.from(url
        ,{
          body: request.body,
         headers: {
        "Content-Type": "multipart/form-data",
       } 
        }
      );
    }
  });
```

Then I get below error:
```json
{
    "timestamp": "2024-11-04T19:59:04.801+00:00",
    "status": 415,
    "error": "Unsupported Media Type",
    "path": "/app/doc/release/"
}
```

I have to use "fastify-file-upload" otherwise I dont see the file in the request body

**Comment by climba03003** [comment]
The `request.body` is required to be either `Buffer`, `ArrayBuffer` or `Stream`, otherwise it cannot be pipe through to the next request.

I would say there is no bug here, you should reconstruct the `FormData` or using another plugin that pipe the raw stream to `request.body`.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by shalakad19** [comment]
> The `request.body` is required to be either `Buffer`, `ArrayBuffer` or `Stream`, otherwise it cannot be pipe through to the next request.
> 
> I would say there is no bug here, you should reconstruct the `FormData` or using another plugin that pipe the raw stream to `request.body`.

If the request is being forwarded to a proxy why is there a need to explicitly specify request.body ? I have not specified request.body for all other GET and POST requests and they work just fine. Only when the request body has a file this issue comes up

**Comment by climba03003** [comment]
> > The `request.body` is required to be either `Buffer`, `ArrayBuffer` or `Stream`, otherwise it cannot be pipe through to the next request.
> > I would say there is no bug here, you should reconstruct the `FormData` or using another plugin that pipe the raw stream to `request.body`.
> 
> If the request is being forwarded to a proxy why is there a need to explicitly specify request.body ? I have not specified request.body for all other POST requests and they work just fine. Only when the request body has a file this issue comes up

When the body is JSON, we helps you to transform back to the appropriate payload. However, it is not the case for `multipart/form-data`.

We cannot and should not helps you to do the transform for `multipart/form-data` because we have no idea what plugin you are using and how the payload is constructed in `request.body`.
