### ISSUE TITLE
Bad Request with undici

### ISSUE THREAD

**Issue by crg-rgo** [fastify/fastify-reply-from#44]
Hi,

I get 400 Bad Requests from some servers if I set the undici option to true. I debugged the code and the problem is, that there is a host header added in fastify-reply-from (https://github.com/fastify/fastify-reply-from/blob/9718e8afd913b00bdf30f121c5798f373292d45c/index.js#L43), but undici already set one at the start (https://github.com/mcollina/undici/blob/120e533e0a638406f0d7f056aa6df207eb9c730a/lib/client.js#L131).

One backend where this error occurs is azure blob storage, for example.

**Comment by mcollina** [comment]
Can you please provide an example to reproduce?

**Comment by crg-rgo** [comment]
Thank you for your fast answer.

I have created a test repository: https://github.com/crg-rgo/reply-from-undici-error.

I hope this helps. I also created a test azure storage account. Do you need it?

**Comment by mcollina** [comment]
Yes, it would be handy to have everything pre-configured so I can just run a script and see the error.

**Comment by crg-rgo** [comment]
Ok, I added the azure storage url to the repository. You just have to start the fastify server (`npm run dev`) and try 2 routes:

http://127.0.0.1:3000/no-undici -> 200
http://127.0.0.1:3000/undici -> 400 Bad Request (Invalid Header)

Does this work for you?
