### ISSUE TITLE
add options to specify certificates

### ISSUE THREAD

**Issue by matth-c3** [fastify/fastify-reply-from#49]
Hello, 

Would it be possible to add the options to specify certificates (ca / key / cert / pfx ) in the https agent ? 

Thanks.

**Comment by mcollina** [comment]
Sure thing, would you like to send a PR?

Il giorno mar 23 apr 2019 alle 07:03 matth-c3 <notifications@github.com> ha
scritto:

**Comment by matth-c3** [comment]
Hello, 

No sorry.

**Comment by matth-c3** [comment]
Hello @mcollina , 

I added the options `cert` and `key` in the `opts` of the plugin, but in the `opts` of the `from`. In my case I use a different certificates based on the endpoint.

before I commit a PR here is what i've [done](https://github.com/matth-c3/fastify-reply-from/tree/dev) 

Let me know.
