### ISSUE TITLE
Pipe body as stream

### ISSUE THREAD

**Issue by parthibd** [fastify/fastify-reply-from#51]
Is this possible with the current version ?

**Comment by Eomm** [comment]
Looking the [todos](https://github.com/fastify/fastify-reply-from#todo) and the source:

https://github.com/fastify/fastify-reply-from/blob/72c677daddcb2c79c7fffd3c851634a507fb1eac/index.js#L49

It seems not for now

Would you like to give it a try? 💪

**Comment by parthibd** [comment]
I sure would love to. But before I write the implementation, can you guide me how should I proceed?

**Comment by parthibd** [comment]
We really need to implement this feature . Can anyone guide me ?

**Comment by Eomm** [comment]
I can try ✌
Let me check the code

**Comment by parthibd** [comment]
That'd be great!

**Comment by Eomm** [comment]
I think that is necessary to:
- add a content parser to manage stream (fastify-multipart plugin could help on this task)
- create a new request to the target url and then pipe the body Stream into it

This should be enough

adding cc @mcollina since he is the king of streams 👑🌊
