### ISSUE TITLE
NOT-AN-ISSUE: Upcoming fork

### ISSUE THREAD

**Issue by jkyberneees** [fastify/fastify-reply-from#55]
Hi fastify-reply-from team, just wanted to share with you this derivate/fork upcoming project:
https://github.com/jkyberneees/req-proxy

Although I properly mention this project as a base on `fast-proxy` fork, I also kept Matteo Collina in the license header. Can I kindly ask for your feedback here? 

Best Regards

**Comment by mcollina** [comment]
Awesome work! Have you changed anything in the internal logic? Would you think It might be worthwhile extracting some of these in its own library that we co-maintain?

**Comment by jkyberneees** [comment]
Hi @mcollina, it's great to hear. 

I do believe there are many reasons for a component like this to be framework agnostic and therefore increase it's adoption. Is nothing we can regret from fastify, it is about the use cases, sometimes developers "just" need a raw proxy without other overhead. 
When we look at the Node.js landscape, `fastify-reply-from` implementation is clearly faster. My plan with `fast-proxy` is to make it available everywhere, removing the fastify dependencies.  

I have found some performance improvements that can be ported back as well, although I want to have the test coverage complete before hand. I would be happy to join efforts on co-maintaining a core component like this, open to your considerations here.

**Comment by mcollina** [comment]
Does it currently depend on restana at all? Would you be ok in sending a PR?
I would still love to have that shared module in the fastify org, if you don't mind.

**Comment by jkyberneees** [comment]
No, is does depends on any specific framework, here you can see a quite "framework less" integration: https://github.com/jkyberneees/req-proxy/blob/master/benchmark/fast-proxy-0http-gateway.js

**Comment by jkyberneees** [comment]
I will try to reintroduce `undici` as an injectable Agent class and then will open the MR. 
I am fine if you would like to host this project on the fastify org, just let me know...

**Comment by mcollina** [comment]
`undici` will also give a speed bump, it's quite faster than Node core http. It's still experimental and there are known bugs... it would require some more work if you are interested as well.

Would you prefer to move the repo or for me to create a new one?

I'll play with what you have and see how much change I'll need to do here to leverage that.

**Comment by jkyberneees** [comment]
Yes, I will support `undici` as well. Just sent you an invitation to the repo, please do as you prefer. 
I could transfer the repo into the fastify org if I would have the rights to. We can manage the npm access afterwards. 

Looking forward to this collaboration...

**Comment by mcollina** [comment]
I've invited you to the org! You should be able to transfer the repo!

**Comment by jkyberneees** [comment]
Great, just in time: https://github.com/jkyberneees/req-proxy/releases/tag/v1.1.0

**Comment by jkyberneees** [comment]
Unfortunately the repo is a fork and github complains because the `fastify-reply-from` project already exists. 
I think it would be easier if you create a new `fast-proxy` repo and push the sources from here: https://github.com/jkyberneees/req-proxy

Regards

**Comment by trygve-lie** [comment]
Has there been any movement on this? 

I am in the situation where I am about to move some projects off `node-http-proxy` but I need to support both fastify and non-fastify http frameworks. In other words; being able to have the core proxy functionality as a http framework agnostic module would be perfect.

I am able to use `fast-proxy` but currently there is now so that this module have some functionality which `fast-proxy` is missing and which I need. 

I would be more than happy to pitch in on getting `fast-proxy` into a standalone core proxy module and align it with this module.

**Comment by jkyberneees** [comment]
Hi @trygve-lie thanks for reaching out.

At the moment `fast-proxy` is framework agnostic, not sure if you noticed that the only thing you would need to proxy an HTTP request is: `proxy(req, res, req.url, {})`
I am also interested on knowing which functionalities are missing according to your requirements. 

Regarding replacing `node-http-proxy`, please consider https://www.npmjs.com/package/fast-gateway, it is so much performant:
![image](https://user-images.githubusercontent.com/4096860/74223592-55c63280-4cb7-11ea-8cf6-3c4ff5191858.png)
https://medium.com/sharenowtech/node-js-api-gateway-a-developer-perspective-8defe575ed21

I would be more than happy on moving fast-proxy to the fastify org, I would be more than happy. Because it is mainly the continuation of the work @mcollina did on `fastify-reply-from`.

However, as it removes all former integration with fastify, I am not sure if it still makes sense. Maybe @mcollina can bring some considerations here. 

Thanks and Regards

**Comment by trygve-lie** [comment]
Thanks for your quick response.

I am aware that `fast-proxy` is framework agnostic but it seems like this module has a little bit more development traction. I liked the initial thought that a core proxy module is framework agnostic and then this module and `fast-gateway` depends upon that one instead of having duplicated code. Then both this project and `fast-gateway` would gain from each other.

In `fast-proxy` I am currently missing the [`.rewriteRequestHeaders`](https://github.com/fastify/fastify-reply-from#rewriterequestheadersoriginalreq-headers) feature which are available in this module. I might also need the [`.body`](https://github.com/fastify/fastify-reply-from#body)  feature in close future.

**Comment by mcollina** [comment]
I'm in favor of moving this on top of `fast-proxy`. I would like to move fast-proxy to this org and get added as an owner on npm. Alternatively, we can move fast-proxy to https://github.com/pillarjs.

@trygve-lie would you volunteer to do the work to rewrite this module on top of fast-proxy?

I've invited both of you to this org anyway.

**Comment by jkyberneees** [comment]
- fast-proxy was moved to the fastify organisation 💚💚💚
- Also invited you as a maintainer for the project on NPM. 

Not sure that I have proper access to the `fast-proxy` project now, @mcollina maybe you can check that? 

Looking forward to your feedback.

**Comment by mcollina** [comment]
You should have admin access, please check!
Il 11 feb 2020, 14:35 +0100, Rolando Santamaria Maso <notifications@github.com>, ha scritto:

**Comment by jkyberneees** [comment]
@mcollina I am, thanks.

**Comment by trygve-lie** [comment]
Sweet :)

I am more than happy to rewrite this module to depend on fast-proxy (actually have a good chunk of time I can spend on it this week). I'll also port existing core features in this repo to fast-proxy.

**Comment by jkyberneees** [comment]
Project is migrated and we are following according to @trygve-lie suggestions. 💚
I am closing this issue.
