### ISSUE TITLE
Rewrite request headers

### ISSUE THREAD

**Issue by konradpe** [fastify/fastify-reply-from#56]
Would you be open to a pull request for a new option to rewrite the request headers similar to your `rewriteHeaders` option? I am actually using the `fastify-http-proxy` module and I need to set the `Host` header to the original value for the upstream to accept the request.

More context: the upstream is Minio and it seems to base the signature on some header values, i.e. the `Host`, e.g. https://github.com/minio/cookbook/blob/master/docs/setup-nginx-proxy-with-minio.md#proxy-all-requests

**Comment by mcollina** [comment]
Definitely, would you like to send a PR?
