### ISSUE TITLE
Always sending requests `application/json` if not a stream

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-reply-from#59]
https://github.com/fastify/fastify-reply-from/blob/97508b89512d07b751bcef3d90ab2441343b1465/index.js#L65-L69

If a `POST` request is sent with a content type of `text/plain` and a body of `this is plain text` then the above branch will be hit and the outgoing request will have the content type header set to `application/json` and the request body will be JSON stringified.

1. The body should not be JSON stringified unless the received payload is designated `application/json`
2. It should pass along the received content type header as-is instead of rewriting it to `application/json`

**Comment by mcollina** [comment]
LOL, this is nice. Would you like to send a PR?

**Comment by jsumners** [comment]
I don't have permission to push my branch up to this repo.

**Comment by mcollina** [comment]
now you do

Il giorno sab 1 giu 2019 alle ore 14:24 James Sumners <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
Closed in #60.
