### ISSUE TITLE
Invalid content-type check

### ISSUE THREAD

**Issue by jkyberneees** [fastify/fastify-reply-from#61]
Hi team, I wanted to report that the following statement:
https://github.com/fastify/fastify-reply-from/blob/4e8718d86443ddb2a0c53c0c629bc8eb6460a315/index.js#L68
Will fail in case of extended content-type formats like: `application/json;charset=utf-8`

Check should be:
```js
body = contentType.toLowerCase().indexOf('application/json') === 0 ? JSON.stringify(this.request.body) : this.request.body
```

Can we fix this one? 
Regards

**Comment by jkyberneees** [comment]
ping @jsumners

**Comment by jsumners** [comment]
@jkyberneees there's no way I'd be able to get to it before Saturday. A PR for `.startsWith()` would be welcome.
