### ISSUE TITLE
Need to cut 1.0.0 release

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-reply-from#63]
This module needs a v1.0.0. Changes like the ones that constituted https://github.com/fastify/fastify-reply-from/releases/tag/v0.6.1 are breaking changes (arguably a fix, but the functionality was established) and get installed automatically from installs of `fastify-http-proxy`. This has undesirable side effects.

**Comment by Eomm** [comment]
> This has undesirable side effects.

is the missing header the case?

Do you think that is necessary to:
- release a `fastify-reply-from` v1 as is right now
- release a patch of `fastify-http-proxy` locking the `fastify-reply-from` to `0.6.0`
- release a major of `fastify-http-proxy` with `fastify-reply-from: ^1.0.0`
?

**Comment by jsumners** [comment]
I think all that is necessary from my point of view is that `fastify-reply-from` get a version bump to v1.0.0. This is merely to state that the module is stable and any future breaking changes will be handled accordingly. Currently, in the 0.x stage it's unstable and should not be a dependency of a stable release (as `fastify-http-proxy` already is).

**Comment by mcollina** [comment]
Done,.

**Comment by jsumners** [comment]
Excellent. Thank you @mcollina.
