### ISSUE TITLE
Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by g45t345rt** [fastify/fastify-reply-from#69]
I think it's because of modifyCoreObjects: false

https://github.com/fastify/fastify-reply-from/blob/81faf95ab3ad83a9f08c145e3f1cb41b6229b479/index.js#L95

**Comment by g45t345rt** [comment]
`this.request.log.info({ source }, 'fetching from remote server') `

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by g45t345rt** [comment]
done

**Comment by Eomm** [comment]
Released in 2.0.1 👍

**Comment by g45t345rt** [comment]
Cool!
Is fastify-http-proxy going to be updated
https://github.com/fastify/fastify-http-proxy/blob/ac003b2391587908725d3842acca408174f394d6/package.json#L45

**Comment by Eomm** [comment]
It is not necessary, you need only to run npm update, the v2.0.1 is the library's semver range

**Comment by g45t345rt** [comment]
I'm **not** using fastify-reply-from but fastify-http-proxy.
It says in the readme that fastify-http-proxy is built on top of fastify-reply-from.
So, I was under the assumption that you need to update fastify-reply-from in the package of fastify-http-proxy. 

Right here: https://github.com/fastify/fastify-http-proxy/blob/ac003b2391587908725d3842acca408174f394d6/package.json#L45

**Comment by jsumners** [comment]
https://nodesource.com/blog/semver-a-primer/#tildecaretshorthand

`npm update --depth 9999 fastify-reply-from`

**Comment by g45t345rt** [comment]
Okay I got it two work but here are my observations

- **nothing happens** -> `npm update` and even `npm update --depth 9999 fastify-reply-from`
- **success** `npm uninstall fastify-http-proxy` followed by `npm install fastify-http-proxy`
- **success** `npm install fastify-reply-from` but I don't need it in my package.json

In other word, reinstalling the package works or installing fastify-reply-from while I had the other package also worked

Maybe just maybe... they have a bug with npm update?

Thanks guys!

**Comment by Eomm** [comment]
The npm version could impact the output and the `package-lock.json` as well.

I use this `npm outdate --depth 999` to check if npm "sees" what I want to update 👍
