### ISSUE TITLE
`rewriteRequestHeaders` unable to access request decorations

### ISSUE THREAD

**Issue by markrzen** [fastify/fastify-reply-from#72]
## 🐛 Bug Report

`rewriteRequestHeaders` unable to access request decorations

## To Reproduce

```js
fastify.decorateRequest('foo', null)
fastify.addHook('preHandler', async (request, reply) => {
  request.foo = 'Bar'
})
fastify.register(require('fastify-http-proxy'), {
  upstream: process.env.UPSTREAM,
  prefix: '/api',
  replyOptions: {
    rewriteRequestHeaders(originalReq, headers) {
      const modifiedHeaders = {
        ...headers,
        'x-foo': request.foo
      }
      return modifiedHeaders
    }
  }
})
```

## Expected behavior

I expect that the request decorations would be accessible via `rewriteRequestHeaders` via the `originalReq` parameter.

## Your Environment

- *node version*: 12
- *fastify version*: 2.13.1
- *os*: Mac

**Comment by Eomm** [comment]
The `req` object is the raw http request, not the Fastify request object.

Would you like to send a PR?
I think that the function could be `bind` to the fastify request

**Comment by jsumners** [comment]
> I think that the function could be bind to the fastify request

Maybe in a major release.

**Comment by markrzen** [comment]
Happy to submit a PR, just wasn't sure if that would be acceptable with the name being `originalReq` I assumed there might be some more intentional real the raw node req was used?

**Comment by jsumners** [comment]
> Happy to submit a PR, just wasn't sure if that would be acceptable with the name being `originalReq` I assumed there might be some more intentional real the raw node req was used?

Hence my desire that this would be a major release.

I'm not particularly clear why it is expected that request decorators would be available here. Seems more like a deficiency in the documentation than anything else.

**Comment by markrzen** [comment]
It could be considered a documentation issue, although almost the entire Fastly ecosystem uses the Fastly Request object, which contains the decorations. This is an outlier to my, likely limited, understanding.
