### ISSUE TITLE
Crash: Source crashes when http2 target goes down or becomes unavailable

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify-reply-from#8]
**Scenario 1:** 
Start source server without starting client. Source process crashes immediatly as it tries to create client connection eagerly.

**Scenario 2:**
1. Start target and then source 
2. Shutdown target service
3. Hit proxied request
Source server crashes as http2 client session becomes invalid after target shutdown

**Proposed Solution:**
1. Lazy initialization of `http2Client` on first request.
2. Setup `error` event listener on `http2Client`.
Planning to return status `500` with `Internal Server Error` as message. **_Any suggestions?_**
3. Check `http2Client.destroyed` flag to determine whether session is valid or not and attempt to reconnect.

Pull request will follow shortly.

**Comment by mcollina** [comment]
If we are forwarding (without rewriting), a 500 is the best thing we can do. I’m not sure we should have some other API to intercept that error.

Can you please verify how we handle the case of a truncated socket?
